# Generated by Django 4.2.13 on 2024-05-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
