# Generated by Django 4.2.13 on 2024-05-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
