# Generated by Django 4.2.13 on 2024-05-20 02:09

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.getfilename),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.getfilename),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.getfilename),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.getfilename),
        ),
    ]
