# Generated by Django 4.2.13 on 2024-05-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product_product_image1_product_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image1',
            new_name='product_image_four',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image2',
            new_name='product_image_one',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image3',
            new_name='product_image_three',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image4',
            new_name='product_image_two',
        ),
    ]
