# Generated by Django 4.2.13 on 2024-05-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_product_image1_product_product_image_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_four',
        ),
    ]
