# Generated by Django 4.2.13 on 2024-05-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='product_size',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
